In [36]:
import numpy as np
import json as js
from json import JSONEncoder

# class NumpyArrayEncoder(JSONEncoder):
#     def default(self, obj):
#         if isinstance(obj, np.ndarray):
#             return obj.tolist()
#         return JSONEncoder.default(self, obj)
    
# a = np.array([[0, 1, 7], [-1 ,0, 7]])


# numpyData = {"array": a}

# with open("numpyData.json", "w") as write_file:
#     js.dump(numpyData, write_file, cls=NumpyArrayEncoder)


with open("numpyData1.json", "r") as read_file:
    decodedArray = js.load(read_file)
    print(decodedArray["array"])
    A = np.asarray(decodedArray["array"])

row, column = A.shape

S = A[0:row, column-row:column, ]
print(S)

B = np.linalg.inv(S)
print(B)



[[0, 1, 0, 1, 1, 0, 0, 1], [1, 1, 1, 0, 0, 1, 0, 0], [1, 0, 0, 1, 1, 0, 1, 0]]
[[0 0 1]
 [1 0 0]
 [0 1 0]]
8
[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
